services:
  traefik:
    image: traefik:v2.11.1
    container_name: traefik
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./traefik.yml:/etc/traefik/traefik.yml
      - ./volumes/letsencrypt:/letsencrypt
    networks:
      - traefik_network
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.traefik.rule=Host(`traefik.${WORDPRESS_DOMAIN_POD}`)"
      - "traefik.http.routers.traefik.service=api@internal"
      - "traefik.http.routers.traefik.entrypoints=websecure"
      - "traefik.http.routers.traefik.tls.certresolver=letsencrypt"
      - "traefik.http.routers.traefik.middlewares=traefik-auth"
      # Basic Authentication for Dashboard
      - "traefik.http.middlewares.traefik-auth.basicauth.users=${TRAEFIK_BASIC_AUTH}"

   # Wordpress for woocommerce print on demand 
  wordpress_pod:
    image: wordpress:latest
    container_name: wordpress_pod
    restart: unless-stopped
    env_file: .env
    depends_on:
      db_pod:
        condition: service_healthy
    networks:
      - traefik_network
      - backend_network
    environment:
      WORDPRESS_DB_HOST: db_pod:3306
      WORDPRESS_DB_USER: ${MYSQL_USER_POD}
      WORDPRESS_DB_PASSWORD: ${MYSQL_PASSWORD_POD}
      WORDPRESS_DB_NAME: ${MYSQL_DATABASE_POD}
    volumes:
      - ./volumes/wp_pod_data:/var/www/html
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.wordpress_pod.rule=Host(`${WORDPRESS_DOMAIN_POD}`)"
      - "traefik.http.routers.wordpress_pod.entrypoints=websecure"
      - "traefik.http.routers.wordpress_pod.tls.certresolver=letsencrypt"
      - "traefik.http.services.wordpress_pod.loadbalancer.server.port=80"
      - "traefik.docker.network=traefik_network"

  db_pod:
    image: mariadb:10.6
    container_name: db_pod
    restart: unless-stopped
    env_file: .env
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD_POD}
      MYSQL_DATABASE: ${MYSQL_DATABASE_POD}
      MYSQL_USER: ${MYSQL_USER_POD}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD_POD}
      MYSQL_PWD: ${MYSQL_ROOT_PASSWORD_POD}
    networks:
      - backend_network
    volumes:
      - ./volumes/mysql_data_pod:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p${MYSQL_ROOT_PASSWORD_POD}"]
      interval: 5s
      timeout: 10s
      retries: 10

networks:
  traefik_network:
    name: traefik_network
    driver: bridge
    attachable: true
    driver_opts:
      com.docker.network.enable_ipv6: "false"
      com.docker.network.bridge.enable_icc: "true"
      
  backend_network:
    name: backend_network
    driver: bridge
    internal: true

  vpn_network:
    driver: bridge
    internal: true

volumes:
  mysql_data:
  wp_pod_data:
  letsencrypt: