api:
  dashboard: true
  insecure: false  # Disable HTTP dashboard access

entryPoints:
  web:
    address: ":8000"
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https

  websecure:
    address: ":8443"  # TLS is implicit here

certificatesResolvers:
  letsencrypt:
    acme:
      email: vedat@thingsmart.co
      storage: /letsencrypt/acme.json
      httpChallenge:
        entryPoint: web

providers:
  docker:
    exposedByDefault: false
    network: traefik_networks